export let quiz = [
    {
        index: 1,
        question: 'Коли ти з друзями під час їжі жваво розмовляєш - є ризик вдавитися. Якщо це трапилося з одним із твоїх друзів, і він почав кашляти, які твої дії,',
        right: 'Спонукати друга відкашлятись.',
        rightExplanation: 'Правильно, якщо він може кашляти, то найкращою допомогою буде залишатися поряд, та спонукати кашляти.',
        wrong1: '',
        wrong1Explanation: '',
        wrong2: '',
        wrong2Explanation: '',
        wrong3: '',
        wrong3Explanation: '',
    },
    {
        index: 0,
        question: '',
        right: '',
        rightExplanation: '',
        wrong1: '',
        wrong1Explanation: '',
        wrong2: '',
        wrong2Explanation: '',
        wrong3: '',
        wrong3Explanation: '',
    },
    {
        index: 0,
        question: '',
        right: '',
        rightExplanation: '',
        wrong1: '',
        wrong1Explanation: '',
        wrong2: '',
        wrong2Explanation: '',
        wrong3: '',
        wrong3Explanation: '',
    },
    {
        index: 0,
        question: '',
        right: '',
        rightExplanation: '',
        wrong1: '',
        wrong1Explanation: '',
        wrong2: '',
        wrong2Explanation: '',
        wrong3: '',
        wrong3Explanation: '',
    },
    {
        index: 0,
        question: '',
        right: '',
        rightExplanation: '',
        wrong1: '',
        wrong1Explanation: '',
        wrong2: '',
        wrong2Explanation: '',
        wrong3: '',
        wrong3Explanation: '',
    },
    {
        index: 0,
        question: '',
        right: '',
        rightExplanation: '',
        wrong1: '',
        wrong1Explanation: '',
        wrong2: '',
        wrong2Explanation: '',
        wrong3: '',
        wrong3Explanation: '',
    },
    {
        index: 0,
        question: '',
        right: '',
        rightExplanation: '',
        wrong1: '',
        wrong1Explanation: '',
        wrong2: '',
        wrong2Explanation: '',
        wrong3: '',
        wrong3Explanation: '',
    },
    {
        index: 0,
        question: '',
        right: '',
        rightExplanation: '',
        wrong1: '',
        wrong1Explanation: '',
        wrong2: '',
        wrong2Explanation: '',
        wrong3: '',
        wrong3Explanation: '',
    },
    {
        index: 0,
        question: '',
        right: '',
        rightExplanation: '',
        wrong1: '',
        wrong1Explanation: '',
        wrong2: '',
        wrong2Explanation: '',
        wrong3: '',
        wrong3Explanation: '',
    },
    {
        index: 0,
        question: '',
        right: '',
        rightExplanation: '',
        wrong1: '',
        wrong1Explanation: '',
        wrong2: '',
        wrong2Explanation: '',
        wrong3: '',
        wrong3Explanation: '',
    },
    {
        index: 0,
        question: '',
        right: '',
        rightExplanation: '',
        wrong1: '',
        wrong1Explanation: '',
        wrong2: '',
        wrong2Explanation: '',
        wrong3: '',
        wrong3Explanation: '',
    },
    {
        index: 0,
        question: '',
        right: '',
        rightExplanation: '',
        wrong1: '',
        wrong1Explanation: '',
        wrong2: '',
        wrong2Explanation: '',
        wrong3: '',
        wrong3Explanation: '',
    },
    {
        index: 0,
        question: '',
        right: '',
        rightExplanation: '',
        wrong1: '',
        wrong1Explanation: '',
        wrong2: '',
        wrong2Explanation: '',
        wrong3: '',
        wrong3Explanation: '',
    },
    {
        index: 0,
        question: '',
        right: '',
        rightExplanation: '',
        wrong1: '',
        wrong1Explanation: '',
        wrong2: '',
        wrong2Explanation: '',
        wrong3: '',
        wrong3Explanation: '',
    },
    {
        index: 0,
        question: '',
        right: '',
        rightExplanation: '',
        wrong1: '',
        wrong1Explanation: '',
        wrong2: '',
        wrong2Explanation: '',
        wrong3: '',
        wrong3Explanation: '',
    },
    {
        index: 0,
        question: '',
        right: '',
        rightExplanation: '',
        wrong1: '',
        wrong1Explanation: '',
        wrong2: '',
        wrong2Explanation: '',
        wrong3: '',
        wrong3Explanation: '',
    },
    {
        index: 0,
        question: '',
        right: '',
        rightExplanation: '',
        wrong1: '',
        wrong1Explanation: '',
        wrong2: '',
        wrong2Explanation: '',
        wrong3: '',
        wrong3Explanation: '',
    },
    {
        index: 0,
        question: '',
        right: '',
        rightExplanation: '',
        wrong1: '',
        wrong1Explanation: '',
        wrong2: '',
        wrong2Explanation: '',
        wrong3: '',
        wrong3Explanation: '',
    },
    {
        index: 0,
        question: '',
        right: '',
        rightExplanation: '',
        wrong1: '',
        wrong1Explanation: '',
        wrong2: '',
        wrong2Explanation: '',
        wrong3: '',
        wrong3Explanation: '',
    },
    {
        index: 0,
        question: '',
        right: '',
        rightExplanation: '',
        wrong1: '',
        wrong1Explanation: '',
        wrong2: '',
        wrong2Explanation: '',
        wrong3: '',
        wrong3Explanation: '',
    },
    {
        index: 0,
        question: '',
        right: '',
        rightExplanation: '',
        wrong1: '',
        wrong1Explanation: '',
        wrong2: '',
        wrong2Explanation: '',
        wrong3: '',
        wrong3Explanation: '',
    },
    {
        index: 0,
        question: '',
        right: '',
        rightExplanation: '',
        wrong1: '',
        wrong1Explanation: '',
        wrong2: '',
        wrong2Explanation: '',
        wrong3: '',
        wrong3Explanation: '',
    },
    {
        index: 0,
        question: '',
        right: '',
        rightExplanation: '',
        wrong1: '',
        wrong1Explanation: '',
        wrong2: '',
        wrong2Explanation: '',
        wrong3: '',
        wrong3Explanation: '',
    },
    {
        index: 0,
        question: '',
        right: '',
        rightExplanation: '',
        wrong1: '',
        wrong1Explanation: '',
        wrong2: '',
        wrong2Explanation: '',
        wrong3: '',
        wrong3Explanation: '',
    },
    {
        index: 0,
        question: '',
        right: '',
        rightExplanation: '',
        wrong1: '',
        wrong1Explanation: '',
        wrong2: '',
        wrong2Explanation: '',
        wrong3: '',
        wrong3Explanation: '',
    },
]